global:
  scrape_interval: 20s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "127.0.0.1:9090" ]
  - job_name: 'kubernetes-node-cadvisor'
    static_configs:
      - targets: [ "127.0.0.1:998" ]
    metrics_path: /api/v1/nodes/localhost.localdomain/proxy/metrics/cadvisor
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /prometheus/k3s/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /prometheus/k3s/token
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: [ "127.0.0.1:999" ]
    metrics_path: /metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [ "127.0.0.1:9187" ]
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ "127.0.0.1:9093" ]

rule_files:
  - /prometheus/am/rules.yml
  - /prometheus/am/system-rule.yaml
  - /prometheus/am/cadvisor-rule.yaml
  - /prometheus/am/kube-state-metrics-rule.yaml
  - /prometheus/am/postgres-exporter-rule.yaml